### ISSUE TITLE
LocalHost

### ISSUE THREAD

**Issue by geomen888** [pcan/node-stomp-protocol#15]
### Description

yarn run v1.6.0
warning package.json: No license field
$ ts-node ./index.ts
Protocol error! { Error: Error parsing header
    at StompFrameLayer.parseHeaders (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/frame.ts:147:32)
    at StompFrameLayer.onData (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/frame.ts:95:30)
    at EventEmitter.StompFrameLayer.stream.emitter.on (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/frame.ts:32:58)
    at EventEmitter.emit (events.js:180:13)
    at EventEmitter.emit (domain.js:422:20)
    at StompEventEmitter.emit (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/model.ts:54:22)
    at StompSocketStreamLayer.onSocketData (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/stream.ts:43:26)
    at Socket.StompSocketStreamLayer.socket.on (/home/geo/AEP/webpack/aep/server/nodejs/node_modules/node-stomp-protocol/src/stream.ts:35:47)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20) details: 'No \':\' in line \'\r\'' }

### Steps to Reproduce

1. [First Step]  ts-node ./index.ts
2. [Second Step] http://localhost:3000
3. [and so on...] --> Error

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

Specify node-stomp-protocol version here and please include the OS and what version of the OS you're running.

### Additional Information
Pls try to implement also docker image + ngnix ssl . Thank U 
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by pcan** [comment]
Hi @geomen888. I cannot understand what you are trying to do from your stacktrace (you did not post your code), but I think you are trying to access to a STOMP protocol server via HTTP (a browser?). Please, have a look the [official STOMP documentation](https://stomp.github.io/): this protocol is not a superset of HTTP, they are completely different protocols.

**Comment by geomen888** [comment]
thanks fo quick feedback ... I know that not http but U are define 
server . listen ( 9999 ,  'localhost' )  in README, it's confused me.

K/R Eugene

**Comment by pcan** [comment]
No problem @geomen888 😃 
The `server.listen(9999,  'localhost' )` refers to a TCP Server Socket listener, as repored in node.js [official documentation](https://nodejs.org/api/net.html#net_server_listen). In order to use the STOMP protocol, the server must listen for TCP connections, then it passes the control to the STOMP session layer, that manages the data flow. If you have any further question don't exitate to ask; otherwise, you can simply close the issue. Thank you for your interest!
