### ISSUE TITLE
Test "STOMP Client & Server over Plain Socket" fails. 

### ISSUE THREAD

**Issue by antonshwab** [pcan/node-stomp-protocol#27]
### Description

Test `STOMP Client & Server over Plain Socket` fails.

**Actual behavior:**

```
STOMP Client & Server over Plain Socket
    1) "before each" hook for "should perform connection"

  0 passing (2s)
  1 failing

  1) STOMP Client & Server over Plain Socket
       "before each" hook for "should perform connection":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/antonshwab/source/gdmn/node-stomp-protocol/test/e2eTests.ts)
      at Hook.Runnable._timeoutError (/Users/antonshwab/source/gdmn/node-stomp-protocol/node_modules/mocha/lib/runnable.js:440:10)
      at Timeout.<anonymous> (/Users/antonshwab/source/gdmn/node-stomp-protocol/node_modules/mocha/lib/runnable.js:251:24)
      at ontimeout (timers.js:425:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)

```

Increasing timout doesn't help. 

### Versions

Fails on versions v0.3.9 - v0.4.2.

**Comment by pcan** [comment]
I just modified `e2eTests.ts` so it waits for server listening before the client issues the connection. The previous version already worked for me so I don't know if this helps; anyway I think the new version is better.

**Comment by antonshwab** [comment]
Hi @pcan.

Now the tests are excellent, thanks.

If interested, here are the results before your commit 07c8a29.

I run the steps above and listening on other port (58999 in my case) run `npm test` 5 times.
Results was not consistent. Here they are:

1.

```
(node:36624) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
  STOMP Client & Server over Plain Socket
(node:36624) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ should perform connection
    ✓ should perform disconnection
    ✓ should handle client-side socket end
    ✓ should handle server-side socket end
    1) "before each" hook for "should disconnect client after error"

  4 passing (2s)
  1 failing

  1) STOMP Client & Server over Plain Socket
       "before each" hook for "should disconnect client after error":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/antonshwab/source/node-stomp-protocol/test/e2eTests.ts)
      at Hook.Runnable._timeoutError (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:440:10)
      at Timeout.<anonymous> (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:251:24)
      at ontimeout (timers.js:425:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)

```

2.

```
(node:36633) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
  STOMP Client & Server over Plain Socket
(node:36633) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ should perform connection
    1) "before each" hook for "should perform disconnection"

  1 passing (2s)
  1 failing

  1) STOMP Client & Server over Plain Socket
       "before each" hook for "should perform disconnection":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/antonshwab/source/node-stomp-protocol/test/e2eTests.ts)
      at Hook.Runnable._timeoutError (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:440:10)
      at Timeout.<anonymous> (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:251:24)
      at ontimeout (timers.js:425:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)
```

3.

```
(node:36642) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
  STOMP Client & Server over Plain Socket
(node:36642) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    ✓ should perform connection
    ✓ should perform disconnection
    ✓ should handle client-side socket end
    ✓ should handle server-side socket end
    ✓ should disconnect client after error

  STOMP Client & Server over WebSocket
    ✓ should perform connection
    ✓ should call onEnd when client closes connection
    ✓ should call onEnd when client listener throws error

  STOMP Frame Layer
    ✓ should send basic CONNECT message
    ✓ should receive basic CONNECT message
    ✓ should send CONNECT message with filtered headers
    ✓ should emit 'end' when disconnected
    ✓ should close stream when closing
    ✓ should include content-length header
    ✓ should omit content-length header when suppress-content-length is truthy
    ✓ should use content-length when present
    ✓ should reject frames bigger than maxBufferSize
    ✓ should reject frames with broken headers
    ✓ should reject partial received frames in case of error
    ✓ should receive a frame in multiple data events, using content-length
    ✓ should receive a frame in multiple data events, using null char
    ✓ should close stream in case of newline flooding attack
    ✓ should disconnect if not receiving the first frame within a certain period of time
    ✓ should keep connection open if receiving the first frame within a certain period of time
    ✓ should reset newline flooding counter after a certain period of time
    ✓ should receive multiple frames in one data event, using content-length
    ✓ should decode escaped characters correctly when receiving frames
    ✓ should close stream when reading an unsupported escape sequence
    ✓ should encode escape characters correctly when sending frames
    ✓ should throw error when sending an unsupported character

  STOMP Server Session Layer
    ✓ should handle valid CONNECT frame
    ✓ should use protocol v.1.0
    ✓ should switch to protocol v.1.1
    ✓ should switch to protocol v.1.2
    ✓ should send ERROR for unhandled protocol version
    ✓ should send ERROR for invalid command
    ✓ should send ERROR if did not received CONNECT yet
    ✓ should send ERROR when catching exceptions from listener
    ✓ should send ERROR for invalid frame
    ✓ should handle protocol error
    ✓ should handle errors thrown during onError execution
    ✓ should send headers and body for SEND frames
    ✓ should handle frames using listener constructor

  STOMP Client Session Layer
    ✓ should send accept-version header in CONNECT frame
    ✓ should switch to protocol v.1.1
    ✓ should switch to protocol v.1.2
    ✓ should handle ERROR frame
    ✓ should handle command internal errors gracefully


  48 passing (175ms)

```

4.

```
(node:36651) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
  STOMP Client & Server over Plain Socket
    1) "before each" hook for "should perform connection"

  0 passing (2s)
  1 failing

  1) STOMP Client & Server over Plain Socket
       "before each" hook for "should perform connection":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/antonshwab/source/node-stomp-protocol/test/e2eTests.ts)
      at Hook.Runnable._timeoutError (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:440:10)
      at Timeout.<anonymous> (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:251:24)
      at ontimeout (timers.js:425:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)

```

5.

```
(node:36677) DeprecationWarning: "--compilers" will be removed in a future version of Mocha; see https://git.io/vdcSr for more info
  STOMP Client & Server over Plain Socket
    1) "before each" hook for "should perform connection"

  0 passing (2s)
  1 failing

  1) STOMP Client & Server over Plain Socket
       "before each" hook for "should perform connection":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/antonshwab/source/node-stomp-protocol/test/e2eTests.ts)
      at Hook.Runnable._timeoutError (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:440:10)
      at Timeout.<anonymous> (/Users/antonshwab/source/node-stomp-protocol/node_modules/mocha/lib/runnable.js:251:24)
      at ontimeout (timers.js:425:11)
      at tryOnTimeout (timers.js:289:5)
      at listOnTimeout (timers.js:252:5)
      at Timer.processTimers (timers.js:212:10)

```

I tried to increase timeout in mocha to 10000 ms. Result stay the same.

Some details:

- node v10.10.0

- macOS 10.13.6
